### ISSUE TITLE
订阅推送缺少失败补偿

### ISSUE THREAD

**Issue by yomea** [Suzzt/dao-cloud#12]
com.junmo.center.core.handler.SubscribeConfigHandler#channelRead0

订阅推送缺少失败补偿

**Comment by Suzzt** [comment]
Good idea!👍  It is true that there is a certain lack of eventual consistency here. Are you willing to submit a PR to solve this problem?

**Comment by yomea** [comment]
I don't think it's necessary anymore. We can solve this problem by incrementally pulling the heartbeat between nodes. If there is time for incremental pulling, I will submit a PR request
