### ISSUE TITLE
优化：ExpireHashMap

### ISSUE THREAD

**Issue by yomea** [Suzzt/dao-cloud#7]
原始代码：
`public ExpireHashMap(int initialCapacity, int time, TimeUnit timeUnit) {
        map = new HashMap(initialCapacity);
        executor = new ScheduledThreadPoolExecutor(1);
        Runnable task = new Runnable() {
            @Override
            public void run() {
                long currentTime = System.currentTimeMillis() / 1_000;
                for (Object obj : map.entrySet()) {
                    Map.Entry<T, Long> entry = (Map.Entry<T, Long>) obj;
                    Long time = entry.getValue();
                    if (currentTime > time) {
                        map.remove(entry.getKey());
                    }
                }
            }
        };
        executor.scheduleAtFixedRate(task, 0, time, timeUnit);
    }`

这过期逻辑不应该定时循环去检查是否过期，浪费不必要的性能

建议：
直接使用 ScheduledExecutorService 设置过期时间，到了过期时间，线程自己会唤醒移除，或者你数据量很大，你用时间轮也可以

**Comment by Suzzt** [comment]
我直接用local cache去实现了它，你可以cr看看https://github.com/Suzzt/dao-cloud/pull/73.
